### ISSUE TITLE
[SUGGESTION] Add scripts to automate installing of dependencies

### ISSUE THREAD

**Issue by MikeModder** [JoshuaDoes/clinet#1]
This is just a minor thing that isn't needed, but I think it would be nice to have bash/batch scripts to install the dependencies all in one _go_ (pun intended).

**Comment by JoshuaDoes** [comment]
I may consider it, but if I do end up adding bash/batch scripts to install all of the dependencies at once then I'll end up having to automate everything else too like including an example starting configuration.

In the end I want people who use Clinet from source to learn as they *go*, just like I am. :P
Installing the dependencies is super easy and doesn't take much time at all, just copy and paste the install commands from each dependency's repo.

**Comment by thejsa** [comment]
`go get`

**Comment by MikeModder** [comment]
Ah, I didn't realize that was the mentality behind the project. That makes sense. Feel free to close this issue if you want

**Comment by JoshuaDoes** [comment]
It's all good, no worries c:
