### ISSUE TITLE
Split commands into separate source files

### ISSUE THREAD

**Issue by thejsa** [JoshuaDoes/clinet#4]
As it stands, all commands are contained in a single, rather large file with over a thousand lines of code. To make maintenance easier these should probably be split up into separate files.

Working on this in my personal fork.

**Comment by thejsa** [comment]
Fixed in #5 - however, it may be beneficial to further componentise Clinet by splitting commands into packages?

**Comment by JoshuaDoes** [comment]
If by packages you mean a command package that contains all of the commands to clean up the root of the source, that'd be a pretty neat thing to have o:

#5 is merged
